using System;
using System.Collections.Generic;
using System.Text;

namespace GooglePayContracts.WalletObjects.Data
{
    public class SmartTap : Google.Apis.Requests.IDirectResponseSchema
    {
        /// <summary>The unique identifier for a smart tap. This value should follow the format issuer ID.identifier
        /// where the former is issued by Google and latter is the Smart Tap id. The Smart Tap id is a Base64 encoded
        /// string which represents the id which was generated by the Google Pay app.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("id")]
        public virtual string Id { get; set; }

        /// <summary>Communication from merchant to user.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("infos")]
        public virtual System.Collections.Generic.IList<IssuerToUserInfo> Infos { get; set; }

        /// <summary>Identifies what kind of resource this is. Value: the fixed string
        /// `"walletobjects#smartTap"`.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("kind")]
        public virtual string Kind { get; set; }

        /// <summary>Smart Tap merchant ID of who engaged in the Smart Tap interaction.</summary>
        [Newtonsoft.Json.JsonPropertyAttribute("merchantId")]
        public virtual System.Nullable<long> MerchantId { get; set; }

        /// <summary>The ETag of the item.</summary>
        public virtual string ETag { get; set; }
    }
}
